spring:
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
